package com.tms.identity.security;

public enum Permission {
  SELF_BOOK,
  CATALOG_MANAGE,
  STAFF_MANAGE,
  TRIP_MANAGE,
  TRIP_READ_ALL,
  TRIP_OPERATE_ASSIGNED,
  COUNTER_SELL,
  BOOKING_READ_ALL,
  BOOKING_CANCEL_OVERRIDE,
  MANIFEST_READ_ALL,
  PAYMENT_COLLECT_ALL,
  PAYMENT_COLLECT_ASSIGNED,
  PAYMENT_CORRECT,
  PAYMENT_REFUND,
  REPORT_READ,
  AUDIT_READ
}
