package com.tms.common.audit;

import static org.junit.jupiter.api.Assertions.*;

import com.tms.TmsApplication;
import jakarta.persistence.EntityManager;
import java.sql.DriverManager;
import java.time.*;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.support.TestPropertySourceUtils;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import testfixture.audit.AuditProbe;

@SpringBootTest(
    classes = {TmsApplication.class, AuditingIntegrationTest.FixtureConfiguration.class})
@ActiveProfiles("test")
@ContextConfiguration(initializers = AuditingIntegrationTest.FixtureSchema.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AuditingIntegrationTest {
  static class FixtureSchema
      implements ApplicationContextInitializer<ConfigurableApplicationContext> {
    public void initialize(ConfigurableApplicationContext context) {
      var env = context.getEnvironment();
      String schema = "audit_test_" + UUID.randomUUID().toString().replace("-", "");
      try (var connection =
              DriverManager.getConnection(
                  env.getRequiredProperty("spring.datasource.url"),
                  env.getRequiredProperty("spring.datasource.username"),
                  env.getRequiredProperty("spring.datasource.password"));
          var sql = connection.createStatement()) {
        sql.execute("CREATE SCHEMA " + schema);
        sql.execute(
            "CREATE TABLE "
                + schema
                + ".audit_probe (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label"
                + " VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ"
                + " NOT NULL)");
      } catch (java.sql.SQLException ex) {
        throw new IllegalStateException("Cannot initialize isolated auditing fixture", ex);
      }
      TestPropertySourceUtils.addInlinedPropertiesToEnvironment(
          context, "spring.jpa.properties.hibernate.default_schema=" + schema);
    }
  }

  static class MutableClock extends Clock {
    Instant now = Instant.parse("2026-01-01T00:00:00Z");

    public ZoneId getZone() {
      return ZoneOffset.UTC;
    }

    public Clock withZone(ZoneId zone) {
      return Clock.fixed(now, zone);
    }

    public Instant instant() {
      return now;
    }
  }

  @TestConfiguration
  @EntityScan(basePackageClasses = AuditProbe.class)
  static class FixtureConfiguration {
    @Bean
    @Primary
    MutableClock fixtureClock() {
      return new MutableClock();
    }
  }

  @Autowired EntityManager em;
  @Autowired PlatformTransactionManager manager;
  @Autowired MutableClock clock;
  @Autowired JdbcTemplate jdbc;

  @Value("${spring.jpa.properties.hibernate.default_schema}")
  String schema;

  @AfterAll
  void removeOnlyOwnedFixture() {
    assertTrue(schema.matches("audit_test_[a-f0-9]{32}"));
    jdbc.execute("DROP SCHEMA " + schema + " CASCADE");
  }

  @Test
  void timestampsPersistAndOnlyUpdatedAtChangesOnUpdate() {
    var tx = new TransactionTemplate(manager);
    Instant created = clock.instant();
    Long id =
        tx.execute(
            status -> {
              var row = new AuditProbe("first");
              em.persist(row);
              em.flush();
              return row.getId();
            });
    tx.executeWithoutResult(
        status -> {
          var row = em.find(AuditProbe.class, id);
          assertEquals(created, row.getCreatedAt());
          assertEquals(created, row.getUpdatedAt());
        });
    clock.now = created.plusSeconds(60);
    tx.executeWithoutResult(
        status -> {
          em.find(AuditProbe.class, id).setLabel("second");
          em.flush();
        });
    tx.executeWithoutResult(
        status -> {
          var row = em.find(AuditProbe.class, id);
          assertEquals(created, row.getCreatedAt());
          assertEquals(clock.instant(), row.getUpdatedAt());
        });
  }
}
