#!/usr/bin/env python3
"""Generate UI role grants from the server's explicit policy; use --check in CI."""
from pathlib import Path
import json,re,sys
root=Path(__file__).resolve().parents[1]
source=(root/'backend/src/main/java/com/tms/identity/security/RolePermissions.java').read_text()
grants={role:re.findall(r'\b[A-Z][A-Z_]+\b',values) for role,values in re.findall(r'case\s+(\w+)\s*->\s*Set.of\((.*?)\)',source,re.S)}
roles=re.findall(r'\b[A-Z][A-Z_]+\b',(root/'backend/src/main/java/com/tms/identity/domain/Role.java').read_text().split('{',1)[1])
assert set(roles)==set(grants), 'Every role must have explicit grants'
output='// Generated by scripts/permissions.py. Edit the backend policy instead.\n// prettier-ignore\nexport default '+json.dumps(grants,indent=2)+';\n'
target=root/'frontend/src/shared/auth/role-permissions.js'
if '--check' in sys.argv:
 assert target.read_text()==output, 'Run python3 scripts/permissions.py after changing role grants'
 print('Role policy verified:',len(grants),'roles')
else:
 target.parent.mkdir(parents=True,exist_ok=True);target.write_text(output)
