spring.config.import=optional:file:./.env[.properties]
server.port=${PORT:8000}
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/tms}
spring.jackson.default-property-inclusion=always
spring.servlet.multipart.enabled=false
spring.web.resources.add-mappings=false
tms.booking-zone=${BOOKING_TIME_ZONE:Asia/Dhaka}
tms.booking-locale=${BOOKING_TIME_LOCALE:en-US}
